### ISSUE TITLE
Make this package available via pip?

### ISSUE THREAD

**Issue by stasiana** [ldo/dbussy#1]
The ability to use the async functionality in Python 3 is very useful as you describe. 

It would be nice to pull the package via pip3 instead of having to clone and install manually. Will you be doing this?

**Comment by ldo** [comment]
Can’t be bothered for now.

**Comment by lf-** [comment]
:(

I wrote a status bar based on asyncio and had to get it to work with pydbus which is almost abandoned and sucks. I failed to find out about this package *because it wasn't on pip*.

Please reconsider your decision as PyPI is critical for package discovery.

**Comment by traverseda** [comment]
Hey @lf- , it's been more than a week from now ;p

**Comment by traverseda** [comment]
Also, @ldo , it's fair that you're too busy to do this, but please don't close issues like this unless you're too busy to maintain the project at all, in which case please indicate you're looking for a new maintainer.

Would you except pull requests for this feature?
