### ISSUE TITLE
type checking in decorator

### ISSUE THREAD

**Issue by jimparis** [ldo/dbussy#10]
The `@ravel.signal` decorator (and others) explicitly checks for the decorated argument to be a `types.FunctionType`, which means you can't use it to wrap a `functools.partial`.  Can this be relaxed to `callable()`?

(Specifically I'm trying to do something like:
```python
handler = ravel.signal(...)(functools.partial(self.propchanged, path))
self.bus.listen_propchanged(path, True, None, handler)
```
since the handlers aren't normally given the object path.)

**Comment by ldo** [comment]
Yeah, that makes sense. Should learn to use `callable` more. Fixed in c58a544564b7a0bed490796fa0f0c9a8c22f7f03.
