### ISSUE TITLE
Argument name=None raises Exception in ravel.method and ravel.signal

### ISSUE THREAD

**Issue by tu500** [ldo/dbussy#11]
It tries to validate the value, which fails for `None`.
Maybe try [this patch](https://github.com/tu500/dbussy)?
Btw: Thanks for the software!

**Comment by ldo** [comment]
Fixed in fc7ace0f60906251f6af2cbead0a56a2ff2e76b2. Thanks.

**Comment by tu500** [comment]
Wow, that was fast. Thank you.
