### ISSUE TITLE
ravel.signal objects_added always has '/' as path

### ISSUE THREAD

**Issue by Snevzor** [ldo/dbussy#17]
I have:

```
self._bus.listen_objects_added(func=self.objects_added)
...
    @ravel.signal(name="object_added",
                  in_signature="oa{sa{sv}}",
                  path_keyword="object_path",
                  args_keyword="args",)
    def objects_added(self, object_path, args):
        logging.warning(object_path)
        logging.warning(args)
```
But object path always is '/' where I, for example, should expect '/org/bluez/hci0/dev_09_6B_A1_1D_B3_E3':

```
22-05-2019 16:23:27.760 WARNING [aioble.objects_added:90] /
22-05-2019 16:23:27.760 WARNING [aioble.objects_added:91] [ObjectPath('/org/bluez/hci0/dev_09_6B_A1_1D_B3_E3'), {'org.bluez.Device1': {'ServicesResolved': (Signature('b'), False), 'Trusted': (Signature('b'), False), 'UUIDs': (Signature('as'), []), 'LegacyPairing': (Signature('b'), False), 'Paired': (Signature('b'), False), 'Adapter': (Signature('o'), ObjectPath('/org/bluez/hci0')), 'Blocked': (Signature('b'), False), 'Connected': (Signature('b'), False), 'Address': (Signature('s'), '09:6B:A1:1D:B3:E3'), 'Alias': (Signature('s'), '09-6B-A1-1D-B3-E3'), 'ManufacturerData': (Signature('a{qv}'), {6: (Signature('ay'), [1, 9, 32, 2, 225, 87, 110, 71, 58, 147, 111, 255, 164, 202, 51, 230, 108, 180, 229, 6, 238, 133, 47, 2, 236, 79, 249])}), 'RSSI': (Signature('n'), -49)}, 'org.freedesktop.DBus.Properties': {}, 'org.freedesktop.DBus.Introspectable': {}}]
```

Perhaps I don't understand it completely yet.

**Comment by ldo** [comment]
So you are listening for signals from a Bluetooth daemon?

A couple of things to try:
* Use a tool like `dbus-send` to send your own signal, with a non-root path, and see if that is picked up.
* Try my signal_listener script from the `dbussy_examples` repo to listen for these Bluetooth signals, and see if that behaves the same as your script.

**Comment by Snevzor** [comment]
Ok I'll do that, thanks.

In meantime, is it expected in the previous example output that object_path is '/' while the first arg is 'ObjectPath('/org/bluez/hci0/dev_09_6B_A1_1D_B3_E3')'? My current work-around is to use the first arg as object_path.

**Comment by ldo** [comment]
I don’t know, I’ve never used any Bluetooth devices.

**Comment by Snevzor** [comment]
So the path '/' is actually correct. It's the path of the ObjectManager that publishes the signal. My workaround is not a workaround but the solution for me.
