### ISSUE TITLE
Bad bus name is not caught immediately

### ISSUE THREAD

**Issue by stasiana** [ldo/dbussy#2]
Issuing the command:

`x = ravel.system_bus()["bad_name"]["/"]`

does not cause an error although the bus name does not exist. One must try to issue a real operation first, such as `x.introspect()`. 

Not sure if the is intended behaviour? This delaying of identify the error makes it more difficult to identify what the problem is as several operations need to be done (naming the bus, naming the path, issuing a request) before an error at any stage is identified.

**Comment by ldo** [comment]
Validating the bus name would mean incurring bus traffic at this point.

Also note that even if I validated the bus name at this point, it could still become invalid later. That’s the nature of a completely asynchronous bus.

**Comment by stasiana** [comment]
Fair enough.

**Comment by stasiana** [comment]
Oops closed by mistake. 

It's fair enough that it doesn't incur traffic yet, but the resulting error doesn't allow for disambiguation of what actually went wrong. For example:

`x = ravel.system_bus()["bad_name"]["/"].get_interface("bad_iface_name")`

raises the exception `dbussy.CallFailed: dbus_message_new_method_call failed` which means the application cannot tell if it is a bad bus name or if it is a bad interface name.

**Comment by ldo** [comment]
That’s all the information I get back from libdbus. If you are aware of some API call I could make to get more info about the failure, I’d love to hear about it.

**Comment by ldo** [comment]
OK, things are a little bit clearer to me now. The problem is not that `badname` does not exist on the bus, but that it is not a valid bus name to begin with.

I have added a simple validation call to pick this up at the point where you try to access the bus peer, even before any traffic is incurred.
