### ISSUE TITLE
New Release 1.x incl. bug fix

### ISSUE THREAD

**Issue by IniterWorker** [ldo/dbussy#23]
Hello,

This commit seems like a bug fix. https://github.com/ldo/dbussy/tree/ae8b2c622d5c91c1e3bc91cee1e960d518d7a921. 

I think it's essential to maintain delivery in mainstream release clean.

Thank you for your work on it,

B.r,

**Comment by ldo** [comment]
I don’t understand the question.

**Comment by IniterWorker** [comment]
I meant your python package dbussy is outdated. When do you want to release a new version with the bug fix linked in my first message?
