### ISSUE TITLE
Low Performance for Fixed Type Arrays

### ISSUE THREAD

**Issue by bkstein** [ldo/dbussy#26]
Performance of sending and receiving DBus messages with arrays of fixed type is low. We implemented DBus services, that transmit messages which contain `ay` arrays. Even for rather short arrays of 10000 elements, we observed runtimes of several seconds for appending and extracting data (see `AppendIter` and `ExtractIter` in dbussy.py). The reason is the generic implementation, which creates an iterator object for every single byte, that is append to or extracted from the DBus data.
@ldo: I solved this problem using the unused implementations `AppendIter.append_fixed_array()` and `ExtractIter.fixed_array` [in a github fork.](https://github.com/bkstein/dbussy)
I would appreciate a review.

**Comment by ldo** [comment]
Fixed as of https://github.com/ldo/dbussy/commit/de6bc1ac9610726bf829d92ed98ba4db229ee615.
