### ISSUE TITLE
Ravel add client paths to server space with listen_signal()

### ISSUE THREAD

**Issue by davesteele** [ldo/dbussy#27]
I'm using ravel for server functions, with appropriate attach_asyncio() and request_name() calls.

I'm also monitoring NetworkManager DBus signals, using the listen_signal() method on the same bus.

This is causing freedesktop interfaces on e.g. /org/freedesktop/NetworkManager to be populated under the local server bus name.

Is this expected behavior?

**Comment by ldo** [comment]
Not sure I understand what that means. Can you post an example script?

**Comment by davesteele** [comment]
https://gist.github.com/davesteele/fbb16bd9d297ca71d18f44e4dcf676ad

**Comment by ldo** [comment]
OK, when I run your script and do an [`introspect_all`](https://github.com/ldo/dbussy_examples/blob/master/introspect_all) on it, I get:

    <!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
    "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
    <node name="/">
        <interface name="org.freedesktop.DBus.Introspectable">
            <method name="Introspect">
                <arg type="s" direction="out"/>
            </method>
        </interface>
        <interface name="org.freedesktop.DBus.Peer">
            <method name="GetMachineId">
                <arg name="machine_uuid" type="s" direction="out"/>
            </method>
            <method name="Ping"/>
        </interface>
        <interface name="org.freedesktop.DBus.Properties">
            <method name="GetAll">
                <arg type="s" direction="in"/>
                <arg type="a{sv}" direction="out"/>
            </method>
            <method name="Get">
                <arg type="s" direction="in"/>
                <arg type="s" direction="in"/>
                <arg type="v" direction="out"/>
            </method>
            <method name="Set">
                <arg type="s" direction="in"/>
                <arg type="s" direction="in"/>
                <arg type="v" direction="in"/>
            </method>
            <signal name="PropertiesChanged">
                <arg type="s"/>
                <arg type="a{sv}"/>
                <arg type="as"/>
            </signal>
        </interface>
        <node name="com">
            <interface name="org.freedesktop.DBus.Introspectable"/>
            <interface name="org.freedesktop.DBus.Peer"/>
            <interface name="org.freedesktop.DBus.Properties"/>
            <node name="Foo">
                <interface name="com.foo">
                    <method name="Foo"/>
                </interface>
                <interface name="org.freedesktop.DBus.Introspectable"/>
                <interface name="org.freedesktop.DBus.Peer"/>
                <interface name="org.freedesktop.DBus.Properties"/>
            </node>
        </node>
        <node name="org">
            <interface name="org.freedesktop.DBus.Introspectable"/>
            <interface name="org.freedesktop.DBus.Peer"/>
            <interface name="org.freedesktop.DBus.Properties"/>
            <node name="freedesktop">
                <interface name="org.freedesktop.DBus.Introspectable"/>
                <interface name="org.freedesktop.DBus.Peer"/>
                <interface name="org.freedesktop.DBus.Properties"/>
                <node name="NetworkManager">
                    <interface name="org.freedesktop.DBus.Introspectable"/>
                    <interface name="org.freedesktop.DBus.Peer"/>
                    <interface name="org.freedesktop.DBus.Properties"/>
                </node>
            </node>
        </node>
    </node>

Are you concerned about the standard interfaces showing up on every node? That’s because Ravel implements them on every node.

**Comment by davesteele** [comment]
My problem is that NetworkManager appears to be part of my published interface, confusing anyone inspecting the service. I guess that means I am concerned about the standard interfaces showing up on a client-only path. Can they, by convention or by option, be eliminated, and does that introduce any issues?

Try viewing the name space using D-Feet.

**Comment by ldo** [comment]
OK, the right fix for this was to completely separate out signal dispatching into its own table, separate from method dispatching. That way the latter can be included in introspection responses, while the former can be omitted. I have also removed some completely unnecessary signal-handling code that would have never been used.

I have retried your example, and that whole last section for /org/freedesktop/NetworkManager now no longer appears in the introspection response. See how that works.

**Comment by davesteele** [comment]
I see that the change is reverted. I'm seeing the same behavior as before.

**Comment by ldo** [comment]
I’m not. Comparing introspection results using `ravel.py` with
hash a663ab6 (from before the rework) versus 20d11f7 (latest as of this moment):

    ldo@theon:dbussy_examples> diff -u before.xml after.xml
    --- before.xml  2020-05-18 16:21:39.333830595 +1200
    +++ after.xml   2020-05-18 16:21:45.573788460 +1200
    @@ -46,19 +46,4 @@
                 <interface name="org.freedesktop.DBus.Properties"/>
             </node>
         </node>
    -    <node name="org">
    -        <interface name="org.freedesktop.DBus.Introspectable"/>
    -        <interface name="org.freedesktop.DBus.Peer"/>
    -        <interface name="org.freedesktop.DBus.Properties"/>
    -        <node name="freedesktop">
    -            <interface name="org.freedesktop.DBus.Introspectable"/>
    -            <interface name="org.freedesktop.DBus.Peer"/>
    -            <interface name="org.freedesktop.DBus.Properties"/>
    -            <node name="NetworkManager">
    -                <interface name="org.freedesktop.DBus.Introspectable"/>
    -                <interface name="org.freedesktop.DBus.Peer"/>
    -                <interface name="org.freedesktop.DBus.Properties"/>
    -            </node>
    -        </node>
    -    </node>
     </node>

(I modified your script to use the session bus rather than the system bus, to avoid having to install it with root privileges, but that shouldn’t matter.)

**Comment by davesteele** [comment]
It's possible I wasn't running the proper version. I tried this on a bigger codebase, and got stopped by a bigger problem. I have an inner decorator that inspects and sets up parts of the "args" and "response" keyword variables before they get passed up to the ravel decorator. That appears to have broken - only a single value is returned by a ravel method now, regardless of the signature. Something must have changed in "response".

I'll assume this problem is solved, based on your diff.
