### ISSUE TITLE
Clarifying how to listen for signals

### ISSUE THREAD

**Issue by stasiana** [ldo/dbussy#3]
I'm having difficulty understanding how to listen for signals using ravel. Consider the following using [pydbus](https://github.com/LEW21/pydbus):

```
from gi.repository import GLib
import pydbus

bluez = pydbus.SystemBus().get("org.bluez", "/")
adap  = pydbus.SystemBus().get("org.bluez", "/org/bluez/hci0")

bluez.onInterfacesAdded   = lambda *args: print("InterfacesAdded: ", *args)
bluez.onInterfacesRemoved = lambda *args: print("InterfacesRemoved: ", *args)
adap.onPropertiesChanged  = lambda *args: print("PropertiesChanged: ", *args)

loop = GLib.MainLoop()
loop.run()
```

This listens for Bluez-related events. I can run `bluetoothctl` and issue `power on`, `power off`, etc. and have the Python script display the resulting signals.

How would I do this using ravel? It is not clear in the documentation what the arguments to `listen_signal` or the decorator should be. Trying to do something like this doesn't work:

```
import ravel
import asyncio

@ravel.signal(name = "PropertiesChanged", in_signature = "(s, a{sv}, as)", args_keyword = "args")
def signal_properties_changed(args):
    print(args)

loop = asyncio.get_event_loop()
bus = ravel.system_bus()
bus.attach_asyncio(loop)
bus.listen_signal("/org/bluez/hci0", True, "org.freedesktop.DBus.Properties", "PropertiesChanged", signal_properties_changed)
loop.run_forever()
```

**Comment by ldo** [comment]
If you look in the companion [dbussy_examples](https://github.com/ldo/dbussy_examples) repo, you will see a few scripts showing example uses of the `@ravel.signal` method decorator. In a server-side interface this is only for introspection, while on the client side you define an actual function, or a method in your interface class, to be called when receiving such a signal.

**Comment by ldo** [comment]
No further questions? Closing.
