### ISSUE TITLE
unregister specific interface

### ISSUE THREAD

**Issue by jvaught** [ldo/dbussy#31]
When trying to unregister a specific interface from a path the unregister fails.

I think the problem may be here:
Line 597:
If interface != None then the list is a list of _Interface objects while if interface == None it's a list of interface names (strings).

**Comment by jvaught** [comment]
proposed fix in #32

**Comment by ldo** [comment]
Yeah, there is an inconsistency. Also I thought it would be handy to accept an interface instance or an interface class. Fixed in 76fd5c8348dd87466146779373bc1a0f3722490f.

**Comment by ldo** [comment]
No more problems?
