### ISSUE TITLE
Example of ravel.ManagedObjectsHandler().get_managed_objects(...)

### ISSUE THREAD

**Issue by thoradia** [ldo/dbussy#34]
Hello,
I would like to replace python dbus by dbussy/ravel
I think I could use `ravel.ManagedObjectsHandler().get_managed_objects(...)` to get the managed objects of `/` at `org.bluez`
I would however not know how to do this, because I do not understand all the variables of the method
I would therefore be very grateful if you could provide an example of how this is done
Thank you in advance

**Comment by ldo** [comment]
`ManagedObjectsHandler.get_managed_objects()` is meant for server-side use. It implements the handling of `GetManagedObjects` method calls from clients. Also the client can conveniently respond to `PropertiesChanged`, `InterfacesAdded` and `InterfacesRemoved` signals by registering listeners with the `listen_propchanged()`, `listen_objects_added()` and `listen_objects_removed()` calls.

For a client to make a `GetManagedObjects` call, it can use a proxy interface constructed by Ravel using either the `get_proxy_interface()` or `get_proxy_interface_async()` calls. There are examples of the use of these calls in the [`dbussy_examples`](https://github.com/ldo/dbussy_examples) repo.

**Comment by thoradia** [comment]
Thank you for that information
