### ISSUE TITLE
How to strip signatures from arguments

### ISSUE THREAD

**Issue by thoradia** [ldo/dbussy#35]
Hello,
I am sure this issue has already been raised, but I could not find an existing solution
Is there a way to strip all the signatures from arguments received from ravel?
I need this to convert a python dbus program to ravel
Thank you in advance for you reply

**Comment by thoradia** [comment]
In the meantime, I have written this:
```
import dbussy

def convert_dbussy(data):
    if isinstance(data, list):
        return [convert_dbussy(item) for item in data]
    if isinstance(data, dict):
        return {key: convert_dbussy(data[key]) for key in data.keys()}
    if isinstance(data, tuple) and isinstance(data[0], dbussy.DBUS.Signature):
        return convert_dbussy(data[1])
    return data
```

**Comment by ldo** [comment]
Is this for variant-type arguments? Remember, you will only see these where you specify a variant type in your signature.

**Comment by thoradia** [comment]
It is indeed for variant-type arguments of signals

**Comment by ldo** [comment]
In that case, the type information is useful. It tells you what type was sent by the requestor.

**Comment by thoradia** [comment]
That may well be, but the current code runs fine if I strip the signatures from the arguments I get with signals
Thank you for your reply
