### ISSUE TITLE
How to pass signatures

### ISSUE THREAD

**Issue by thoradia** [ldo/dbussy#36]
Hello again
I trying to find out how to use ravel to call the SetProperty method below with `name='Name'` and `value=['A', 'B']`
```
<method name="SetProperty">
    <arg name="name" type="s" direction="in"/>
    <arg name="value" type="v" direction="in"/>
</method>
```
Thank you for your help

**Comment by ldo** [comment]
The corresponding argument value will need to be a list or tuple of 2 values, being the type signature and the value of that type.

**Comment by thoradia** [comment]
I did it like [this](https://github.com/LibreELEC/service.libreelec.settings/blob/master/src/resources/lib/dbus_connman.py#L24-L25)

**Comment by ldo** [comment]
I don’t see any variants in that example?

**Comment by thoradia** [comment]
The code is moving fast
I will submit my code as an example when I am done
