### ISSUE TITLE
Exceptions in asynchronous property setting not propagated to the user code

### ISSUE THREAD

**Issue by Jajcus** [ldo/dbussy#48]
Hi,

When trying to interact with Bluez using dbussy/ravel I found out that errors in asynchronous property setting cannot be properly handled, instead I get error message:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<def_proxy_interface.<locals>.def_prop.<locals>.set_prop.<locals>.sendit() done, defined at /usr/local/lib/python3.7/dist-packages/ravel.py:2967> exception=DBusError('org.bluez.Error.Failed -- Not Powered')>
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/ravel.py", line 2977, in sendit
    raise dbus.DBusError(reply.error_name, reply.expect_objects("s")[0])
      dbussy.DBusError: org.bluez.Error.Failed -- Not Powered
```

In this case I would like to ignore this specific exception, but I cannot, as it is never propagated to my code.
That is because the error is raised from the sendit() coroutine, which is started as an untracked task.

I can see two possible solutions to that:
* instead of raising the exception sendit() could set it on the set_prop_pending future (instead of setting its result to None)
* alternatively the sendit() tasks could be stored instead of the set_prop_pending futures – that can be awaited the same way

**Comment by ldo** [comment]
Anything further on this issue?

**Comment by Jajcus** [comment]
No, the two changes you made (exception handling and new set_prop()) look ok. Though, I have not tried them yet.
