### ISSUE TITLE
Blocking server calls

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [ldo/dbussy#5]
Hi,
here is the background, just want to see if this is conceptually possible. 

I'm in a situation in which I inherited code that is based on callbacks. 
It implements it's own event loop hidden somewhere in the underlying libraries.

Is it possible to use dbussy to expose a D-bus connection with blocking code and
expect it as something that will happen quick?

Given that this was a horribly phrased question, here is an example :)

Say that I have a callback `new_connection_detected` triggered by a new socket connection. 
Does dbussy offer a way a blocking way to expose existence of the new connection 
as a d-bus interface.
In pseudo code:

```
def new_connection_detected( connection ):
    debussy.expose("new.connection.1")  
```

The use case is just to have a public exposition of the state through d-bus,
there won't be any interaction happening through d-bus.

**Comment by TheMeaningfulEngineer** [comment]
Somewhere below it is, combined with the glib's event loop.

**Comment by ldo** [comment]
So can you get back a `DBusConnection` pointer from it?

**Comment by TheMeaningfulEngineer** [comment]
It uses `dbus.SystemBus()` from `dbus-python`. That kind of looks like the best candidate I have atm for  what you've asked. :)

https://github.com/getsenic/gatt-python/blob/master/gatt/gatt_linux.py#L33

**Comment by ldo** [comment]
DBussy is not compatible with `dbus-python`. As far as I know, there is no way to ask the latter for the underlying `DBusConnection` pointer from `libdbus`. Sorry.

**Comment by TheMeaningfulEngineer** [comment]
All good, thanks.

Just for me to understand, to be able to have a dbus interface registered there needs
to be an event loop running (or any kind of a dedicated d-bus application) somewhere to maintain it?

When I referred to:
> dbussy to expose a D-bus connection with blocking code

I was coming with an analogy of spraying a message on a wall. Where `a wall` was the underlying system bus, and `spraying a message` was the the synchronous blocking call. So once you spray it it stays on the wall regardless of the spray. Seems like this was wrong :)

**Comment by ldo** [comment]
DBussy stores the underlying `libdbus` pointers as low-level `ctypes.c_void_p` values, so you can peek at these and take your life in your hands with it if you choose. But `dbus-python` hides all that within its C code, where you can’t get at it.
