### ISSUE TITLE
Move away from distutils

### ISSUE THREAD

**Issue by rossburton** [ldo/dbussy#52]
As of Python 3.10 distutils is deprecated and will be removed in 3.12:

https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated

Migrating to setuptools will be fairly trivial.

**Comment by ldo** [comment]
Your version of `setup.py` doesn’t seem to match up with mine.

Ah, I see you want to check for version numbers rather than functionality. I disapprove.
