### ISSUE TITLE
unlisten_signal error

### ISSUE THREAD

**Issue by jimparis** [ldo/dbussy#9]
```python
if rulekey in listeners :
    listeners = listeners[rulekey]
    try :
        listeners.pop(listeners.index(func))
    except ValueError :
        pass
    #end try
    if len(listeners) == 0 :
        ignore = dbus.Error.init()
        self.connection.bus_remove_match \
          (
            _signal_rule(path, fallback, interface, name),
            ignore
          )
        del listeners[rulekey]
```
That `del` raises `TypeError`, because `listeners` is no longer the dictionary due to the assignment in line 2.

**Comment by ldo** [comment]
Just some confusion over the meaning of the `listeners` variable -- fixed in 9fa9c658cf4a31c1063d9a3580c51812794b4472. Thanks for the report.

**Comment by Snevzor** [comment]
Hello @ldo. When do you plan a new release? I'm suffering from the same issue but I don't want to fork.

**Comment by ldo** [comment]
Same issue with the current version?

**Comment by Snevzor** [comment]
@ido that's weird. I've installed 1.1 using pip and I have the above mentioned error:
`  File "/home/sven/projects/dbussy-example/venv/lib/python3.5/site-packages/ravel.py", line 644, in unlisten_propchanged
    func = func,
  File "/home/sven/projects/dbussy-example/venv/lib/python3.5/site-packages/ravel.py", line 611, in unlisten_signal
    del listeners[rulekey]
TypeError: list indices must be integers or slices, not tuple
`

**Comment by ldo** [comment]
PyPI version is old, needs updating.
